// Generated by @nuxt/eslint during `nuxt prepare` (postinstall).
// Run `npm install` followed by `npm run lint` to verify.
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt({
  rules: {
    // PrimeVue components require explicit closing tags in some cases
    'vue/html-self-closing': 'off',
  },
})
