apiVersion: v1
kind: Service
metadata:
  name: chronos-backend
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.namespace }}-backend
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- include "chronos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: chronos-backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.containerPort }}
      protocol: TCP
      name: http
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.targetPort }}
      protocol: TCP
      name: metrics
    {{- end }}
