apiVersion: apps/v1
kind: Deployment
metadata:
  name: chronos-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chronos.labels" . | nindent 4 }}
spec:
  {{- if not .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.frontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: chronos-frontend
  template:
    metadata:
      labels:
        app: chronos-frontend
    spec:
      imagePullSecrets:
        - name: chronos-docker-secret
      containers:
        - name: chronos
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          env:
            {{- range $key, $value := .Values.frontend.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range .Values.frontend.envFromSecrets }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .secretKey }}
            {{- end }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
