apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: bitwardensecret-sample
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sm-operator
  name: chronos-secret
  namespace: {{ .Values.namespace }}
spec:
  organizationId: {{ .Values.secrets.organisationId }}
  secretName: chronos-secret
  onlyMappedSecrets: true # default is true
  map:
    - bwSecretId: {{ .Values.secrets.db.password }}
      secretKeyName: database_password
    - bwSecretId: {{ .Values.secrets.backend.clientId }}
      secretKeyName: backend_client_id
    - bwSecretId: {{ .Values.secrets.backend.clientSecret }}
      secretKeyName: backend_client_secret
    - bwSecretId: {{ .Values.secrets.frontend.clientId }}
      secretKeyName: frontend_client_id
    - bwSecretId: {{ .Values.secrets.imagePullSecret  }}
      secretKeyName: container_registry_secret
    - bwSecretId: {{ .Values.secrets.vapid.publicKey  }}
      secretKeyName: vapid_public_key
    - bwSecretId: {{ .Values.secrets.vapid.privateKey  }}
      secretKeyName: vapid_private_key
    - bwSecretId: {{ .Values.secrets.vapid.mailto  }}
      secretKeyName: vapid_mailto
    - bwSecretId: {{ .Values.secrets.backup.s3.bucket  }}
      secretKeyName: backup_bucket
    - bwSecretId: {{ .Values.secrets.backup.s3.access_key_id  }}
      secretKeyName: backup_access_key_id
    - bwSecretId: {{ .Values.secrets.backup.s3.secret_access_key  }}
      secretKeyName: backup_secret_access_key
    - bwSecretId: {{ .Values.secrets.backup.s3.region  }}
      secretKeyName: backup_region
    - bwSecretId: {{ .Values.secrets.backup.s3.endpoint_url  }}
      secretKeyName: backup_endpoint_url
  authToken:
    secretName: bw-auth-token
    secretKey: token
