CREATE SEQUENCE users_SEQ START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE groups_SEQ START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE message_SEQ START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE pushsubscription_SEQ START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE settings_SEQ START WITH 1 INCREMENT BY 50;