# --- OIDC / Keycloak ---
quarkus.oidc.auth-server-url=${AUTH_SERVER_URL}
quarkus.oidc.client-id=${AUTH_SERVER_CLIENT_ID}
quarkus.oidc.credentials.secret=${AUTH_SERVER_CLIENT_SECRET}
quarkus.oidc.roles.role-claim-path=realm_access/roles

# --- Datenbank (Postgres) ---
quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=${DB_USER}
%prod.quarkus.datasource.password=${DB_PASSWORD}
%prod.quarkus.datasource.jdbc.url=${DB_URL}

# Hibernate schema generation (dev: update, prod: validate/migrate via Flyway)
quarkus.hibernate-orm.database.generation=update

quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.store-schema-directory=target

push.vapid.mailto=mailto:admin@chronos-live.de
push.vapid.public=${VAPID_PUBLIC}
push.vapid.private=${VAPID_PRIVATE}