# --- OIDC / Keycloak ---
quarkus.oidc.auth-server-url=${AUTH_SERVER_URL}
quarkus.oidc.client-id=${AUTH_SERVER_CLIENT_ID}
quarkus.oidc.credentials.secret=${AUTH_SERVER_CLIENT_SECRET}
quarkus.oidc.roles.role-claim-path=realm_access/roles

# --- Datenbank (Postgres) ---
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=${DB_URL}

# --- Connection Pool (Agroal) ---
quarkus.datasource.jdbc.min-size=10
quarkus.datasource.jdbc.max-size=50
quarkus.datasource.jdbc.acquisition-timeout=30S

quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.baseline-version=1.0.0
quarkus.flyway.locations=db/migration

push.vapid.mailto=mailto:${VAPID_MAILTO}
push.vapid.public=${VAPID_PUBLIC}
push.vapid.private=${VAPID_PRIVATE}

quarkus.live-reload.instrumentation=true

# Micrometer aktivieren
quarkus.micrometer.enabled=true

# Prometheus-Exporter einschalten
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/metrics

# Enable @Timed annotation support
quarkus.micrometer.binder.mp-metrics.enabled=true

# HTTP-Server Metrics aktivieren (Standard)
quarkus.micrometer.binder.http-server.enabled=true
# HTTP Metrics aktivieren, aber bestimmte URIs ignorieren
quarkus.micrometer.binder.http-server.ignore-patterns=^\/metrics$
quarkus.micrometer.binder.http-client.suppress4xx-errors=true

# File Logging aktivieren
quarkus.log.file.enabled=true
quarkus.log.file.path=./logs/application.log
quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n

# Rotation konfigurieren
quarkus.log.file.rotation.max-backup-index=10
quarkus.log.file.rotation.file-suffix=.yyyy-MM-dd
quarkus.log.file.rotation.rotate-on-boot=true